### ISSUE TITLE
Use container interface when creating ORM instance

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/cycle-bridge#1]
For the following block of code in the bootloader:

```
    private function orm(
        FactoryInterface $factory,
        SchemaInterface $schema = null
    ): ORMInterface {
        return new ORM($factory, $schema);
    }
```

It would be great to use the container with autowire. The idea is that people could include `cycle/entity-behaviour` and declare their own `CommandGeneratorInterface` binding it to `EventDrivenCommandGenerator`.

Or maybe this could somehow be configured via config?

**Comment by butschster** [comment]
Hi, @rauanmayemir. Thank you for your suggestion. 

I've just finished working on this issue, could you please check the result #2? Maybe do you have any additional suggestions?

**Comment by rauanmayemir** [comment]
Perfect. 👌
