### ISSUE TITLE
[Feature Request] Create empty migrations

### ISSUE THREAD

**Issue by iGrog** [spiral/cycle-bridge#76]
Enable the capability to create empty migrations. 
A file with the correct name should be generated. 
Currently, according to the documentation https://cycle-orm.dev/docs/database-migrations/current/en#create-a-migration, 
it is possible to create migrations with any name, but in reality, the name should follow a specific format, including a timestamp, chunk, and name.

**Comment by butschster** [comment]
Hi! Sorry for a long answer. There is `php app.php create:migration` scaffolder command. 

For example 

```bash
php app.php create:migration create_user_table
```

will create a file `20240103.060802_0_create_user_table.php` with the following content

```php
<?php

declare(strict_types=1);

namespace App;

use Cycle\Migrations\Migration;

class CreateUserTableMigration extends Migration
{
    /**
     * Create tables, add columns or insert data here
     */
    public function up(): void
    {
    }

    /**
     * Drop created, columns and etc here
     */
    public function down(): void
    {
    }
}
```
