### ISSUE TITLE
Unable to create token

### ISSUE THREAD

**Issue by jenky** [spiral/cycle-bridge#85]
- Postgres 16.1
- PHP 8.3.1

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bytea
CONTEXT:  unnamed portal parameter $5 = '...'
```

The payload contains an url. Upon `json_encode`, it will add backslashes to escape the uri i.e `http:\/\/127.0.0.1:8080\/` which I guess somewhat invalid for `bytea` column. Removing the URL from the payload resolves the issue.

**Comment by roxblnfk** [comment]
Hello. Could you reopen this in https://github.com/cycle/database?
